FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
ARG CACHEBUST=3
RUN apt-get update
RUN apt-get install -y python3 && apt-get install -y python3-pip && apt-get install -y git && apt-get install -y nvidia-cuda-toolkit
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN chmod 777 /opt/
